# Generated by Django 3.1.7 on 2021-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfernews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('player_image', models.CharField(max_length=2083)),
                ('player_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='fixtures',
            name='competition_image',
            field=models.CharField(default='ucl', max_length=2083),
            preserve_default=False,
        ),
    ]
