# Generated by Django 3.1.7 on 2021-04-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210408_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfernews',
            name='player_description',
            field=models.CharField(max_length=3000),
        ),
    ]
