# Generated by Django 3.1.7 on 2021-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_transfernews_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='venue_image',
            field=models.CharField(default='ucl', max_length=2083),
            preserve_default=False,
        ),
    ]
