# Generated by Django 3.1.7 on 2021-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20210506_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='bio',
            field=models.TextField(default='h'),
            preserve_default=False,
        ),
    ]
