# Generated by Django 3.1.7 on 2021-05-22 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_players_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='fixture_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
